export const ENV = {
  API_URL: process.env.EXPO_PUBLIC_API_URL!,
  GOOGLE_ANDROID_CLIENT_ID: process.env.EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID!,
  GOOGLE_IOS_CLIENT_ID: process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID!,
  GOOGLE_WEB_CLIENT_ID: process.env.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID!,
  RZP_CLIENT_ID: process.env.EXPO_PUBLIC_RAZORPAY_KEY_ID!,
  SOCKET_URL: process.env.EXPO_PUBLIC_SOCKET_URL!,
};
